ryanmcgrath/twython

twython/streaming/types.py
Currently a stream allows for an initial filter list, however it would be useful to dynamically update the filter params in mid stream.  ```TwythonStreamerTypesStatuses``` was updated with a secondary dynamic filter that does not break the current API and supplies a setter function to update the filter.
=> Added dynamic filtering to streamer

docs/usage/advanced_usage.rst
Updated advanced usage documentation to use cursor instead of search_gen
=> search_gen in Advanced usage deprecated

docs/usage/special_functions.rst
Was skimming the docs and noticed this.
=> special_functions.rst: typo: excepts → accepts

docs/usage/advanced_usage.rst
Previously, these examples were using deprecated API endpoints.  This updates the examples accordingly.
=> Update advanced example documentation for uploading images

twython/endpoints.py
The documentation states that users/lookup requires a GET and not a POST.
=> Have lookup_user GET and not POST

AUTHORS.rst
Cory Dolphin changed Github usernames from "wcdolphin" to "corydolphin".
Github does not automatically redirect profile links when you change
usernames so his link in the AUTHORS file went to a 404.
https://help.github.com/articles/what-happens-when-i-change-my-username/#changes-that-arent-automatic
=> Update Cory Dolphin's Github username in AUTHORS.

twython/api.py
Example: Here's a quoted tweet #test https://twitter.com/Android/status/632196209797533696
Generated html (with linebreaks and comments for readability):
```html
Here's a quoted tweet <a href="https://twitter.com/search?q=%23test" class="twython-hashtag">#test</a> 
<a href="https://t.co/H3ru0zGahf" class="twython-url">twitter.com/Android/status…</a>
<blockquote class="twython-quote">
What’s <a href="https://twitter.com/search?q=%23Android" class="twython-hashtag">#Android</a> 
M gonna be? We all have our guesses… <a href="http://t.co/ofHffMu7ME" class="twython-url">g.co/go/NLwhatsM</a> 
<a href="https://twitter.com/search?q=%23natandlo" class="twython-hashtag">#natandlo</a> 
<a href="http://t.co/um6zpIdiw4" class="twython-media">pic.twitter.com/um6zpIdiw4</a>
<cite><a …
```
=> Add support for quoted_status in html_for_tweet()

twython/api.py
Remove redundant checking for oauth_token & oauth_token_secret when using OAuth1 method from requests_oauthlib, because it is already handling None values for us.
=> Remove redundant checking for oauth_token & oauth_token_secret

docs/usage/advanced_usage.rst, twython/api.py, twython/endpoints.py
This is a simple implementation of twitter's [chunked media upload api](https://dev.twitter.com/rest/public/uploading-media#chunkedupload). Following points need to be noted:
- I have added a separate endpoint for this instead of using the `upload_media`.
- It needs a media_type as required by twitter. Though in my own project, I am using python mimetypes module.
- It uses `.seek` to calculate size of media file if not given.
- As twitter have a limit of 5mb per chunk upload, I am uploading in 1mb chunks. I had to use `StringIO` as `helpers._transparent_params` is checking for `read` attribute on file contents.
Please let me know what you guys think.
=> Add chunked video upload functionality

twython/api.py
Older saved tweets (before quote status implementation) do not have 'is_quote_status'. This fixes it for those cases.
=> Fix html_for_tweet for pre-quote implementation

twython/api.py
When the quoted tweet is deleted, Twitter returns ``is_quote_status`` as true, but there is no corresponding ``quoted_status``.
=> Fix issue where is_quote_status is true but there is no quoted_status

twython/endpoints.py
Needed to use BytesIO instead of StringIO when uploading video to Twitter.
Tested with python 2.6.9, 2.7.11, 3.3.6, 3.5.1.
fixes #422
=> Fix upload_video "string argument detected, got 'bytes'" bug.

twython/endpoints.py
Twitter recently announced support for longer duration videos https://twittercommunity.com/t/api-support-for-140-second-video/69153 but to take advantage of that, the media must be uploaded via the async method.
The async media upload method requires an additional STATUS command, but unlike the other commands such as INIT, APPEND, FINALIZE, the STATUS command is a GET request. The patch switches the upload_media endpoint to use self.get() if the command param is 'STATUS'.
=> Use GET request if the media upload command is STATUS

get_direct_message example
added a get_direct_message example hope this is helpful. I spent a lot of time trying to figure it out and figured I could help others with the same problem
=> added get_direct_message example

tests/test_core.py, twython/api.py
This PR adds a check when creating a cursor to ensure that the first argument is callable. This fixes #452.
=> Raise TypeError when cursor is not provided a callable

docs/index.rst
Hi,
old link is now outdated and broken
i propose this one https://developer.twitter.com/en/docs
regards
=> update the link to the doc of the twitter API

twython/api.py, twython/endpoints.py
I have added the create_metadata endpoint for image descriptions. Now it should pass all tests. The following modifications have been made to api.py:
* JSON exception will raise only if response content is not empty.
* _transparent_params is only called if params is a dictionary
=> Added create_metadata endpoint

README.rst, docs/usage/basic_usage.rst, twython/endpoints.py, twython/streaming/api.py, twython/streaming/types.py
Addresses #455; lots of Twitter's documentation links have been recently broken. This PR attempts to update URLs to documentation where it can.
The nice part about this task is that one can grep for `dev.twitter.com` and get a list of deprecated/broken links that need fixing.
=> Update links to Twitter docs

HISTORY.rst, twython/endpoints.py, twython/streaming/types.py
Hello again. This is a small proposed change, simply because I kept getting annoyed looking at the docs and needed to fix it.
1. I wrapped any of the declared params in double backticks
2. I added a few `meth` links
3. I changed "ID" to "id" because Twitter's docs say "ID", but the actual param is the lowercase "id" (both in Twitter examples and what Twython uses)
=> - Cleaned up some docstrings with Sphinx markup and param names.

tests/test_html_for_tweet.py, tests/tweets/entities_with_prefix.json, twython/api.py
If a tweet had a prefix (@names that it was replying to) then the length
of these is counted in the indices that show the locations of entities
within the tweet. But we were applying those indices to the 'display'
part of the tweet that doesn't include the prefix.
So, if the tweet was:
@bob Please meet @bill
and the prefix was `@bob `, then the indices for linking `@bill`
are something like `17,21`. But we were applying the link around
`@bill` to the display text part of the tweet, which is:
Please meet @bill
And so the indices no longer lined up with `@bill`.
Now they do, and the same for URLs and hashtags.
=> Fix links in tweets when there's a prefix

twython/api.py, twython/endpoints.py
This adds support for the new event based direct messages methods, available after August 16. In particular, get_direct_messages, get_direct_message, send_direct_message and destroy_direct_message were changed to the new methods provided in Twitter. Take into account that new objects (events) are returned for all GET methods related to direct messages, and in order to send a direct message you have to send an event in a dictionary as specified in the [Documentation of this method.](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/new-event.html) Also, the function get_send_messages should be removed, as is no longer possible to use that endpoint.
=> Added support for the new direct message endpoints

docs/usage/advanced_usage.rst
Python 2 support was dropped from Twython, thanks!
In Python3 we actually have to use BytesIO, see https://github.com/python-pillow/Pillow/issues/2205
=> update example for a post involving image editing

twython/api.py
=> Fix #522 (needed bc of PEP 479)
